server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/