spring:
  application:
    name: user-service
  profiles:
    active: dev

  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true