spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/clinic
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

  application:
    name: APPOINTMENT

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/